### ISSUE TITLE
Declaration of App\Exports\PostsFromCollection::collection() must be compatible with Vitorccs\LaravelCsv\Concerns\FromCollection::collection(): Illuminate\Support\Collection

### ISSUE THREAD

**Issue by seabasss** [vitorccs/laravel-csv#1]
Thanks, this package looks great!

I can't figure out how to use the `FromCollection` feature. It's the only one without any examples. 
I'm trying this:

```php
public function collection()
{
    return Post::all();
}
``` 
But I'm getting this: 
```
Declaration of App\Exports\PostsFromCollection::collection() must be compatible with Vitorccs\LaravelCsv\Concerns\FromCollection::collection(): Illuminate\Support\Collection
``` 
Ideas? Thank you!

**Comment by seabasss** [comment]
Fixed it:
```php
public function collection(): Collection
{
    return Post::all();
}
```

Minor detail. The example page say `public function query();`. This should be `public function query()` right?

**Comment by vitorccs** [comment]
Hi @seabasss 

Thanks for the feedback.

That's correct - it should be `public function query` without the semicolon `;`.

I have just fixed the README file and also added a new section "Data sources" with more samples:
https://github.com/vitorccs/laravel-csv#data-sources

**Comment by seabasss** [comment]
> Hi @seabasss
> 
> Thanks for the feedback.
> 
> That's correct - it should be `public function query` without the semicolon `;`.
> 
> I have just fixed the README file and also added a new section "Data sources" with more samples: https://github.com/vitorccs/laravel-csv#data-sources

Amazing! Thank you so much! Exports are working great!
